# Generated by Django 4.0.1 on 2022-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.TextField()),
                ('container_status', models.BooleanField()),
                ('container_id', models.TextField()),
                ('request_client_name', models.CharField(max_length=50)),
            ],
        ),
    ]
