# Generated by Django 4.0.1 on 2022-01-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_request_client_name_dashboard_clientname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='ctnName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='ctnPort',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
