# Generated by Django 4.0.1 on 2022-01-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_container_delete_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='ctnStatus',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ctnIP',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ctnToken',
            new_name='jupyterToken',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ctnName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='ctnPort',
            new_name='port',
        ),
    ]
